#!/usr/bin/env node
/**
 * FROZEN behaviour probe — loop `.cursor/loops/dsh-plugin-advisories`.
 *
 * Asserts the bash-guard contract against the *built* plugin (`dist/`, what DSH loads).
 * Build first: `pnpm exec tsc -p plugins/dsh-agent-looper/tsconfig.json`.
 *
 * Do not edit this file to match the implementation. A failing case is the worker's task.
 * Exit 0 = every case holds.
 */

const PLUGIN_DIST = new URL('../../../plugins/dsh-agent-looper/dist/', import.meta.url)
const guard = await import(new URL('nested-run.js', PLUGIN_DIST))
const plugin = await import(new URL('index.js', PLUGIN_DIST))

const RUN = 'agent-loop run .cursor/loops/x'
const failures = []
let checks = 0

function expect(label, actual, wanted) {
  checks += 1
  if (actual === wanted) {
    console.log(`ok   ${label}`)
    return
  }
  failures.push(label)
  console.log(`FAIL ${label} — wanted ${JSON.stringify(wanted)}, got ${JSON.stringify(actual)}`)
}

function expectTrue(label, value) {
  expect(label, Boolean(value), true)
}

function expectDenied(label, reason) {
  expect(label, typeof reason === 'string' && reason.length > 0, true)
}

// ---------------------------------------------------------------- grind guard
const MUST_DENY = [
  ['plain invocation', 'agent-loop run .cursor/loops/x'],
  ['pnpm exec invocation', 'pnpm exec agent-loop run .cursor/loops/x'],
  ['repo script', 'pnpm run agent:loop'],
  ['batch bin', 'agent-loop-batch .cursor/loops'],
  ['batch dist entrypoint', 'node dist/cli/run-batch.js .cursor/loops'],
  ['ts source entrypoint', 'pnpm exec tsx src/cli/run.ts .cursor/loops/x'],
  ['shell wrapper', 'bash -c "agent-loop run .cursor/loops/x"'],
  ['executed heredoc (bash)', `bash <<'EOF'\n${RUN}\nEOF`],
  ['executed heredoc (sh -s)', `sh -s <<'EOF'\n${RUN}\nEOF`],
]

const MUST_ALLOW = [
  ['help', 'agent-loop --help'],
  ['pnpm exec help', 'pnpm exec agent-loop --help'],
  ['init', 'agent-loop-init'],
  ['data heredoc writing package.json', `cat > package.json <<'EOF'\n  "agent:loop": "${RUN}"\nEOF`],
  ['rg mention', 'rg "agent-loop run" docs/'],
  ['git log --grep mention', 'git log --grep="agent-loop run"'],
  ['commit message mention', 'git commit -m "docs: explain why agent-loop run must be backgrounded"'],
  ['sed rewrite mention', 'sed -i "s|agent-loop run|x|" README.md'],
]

console.log('--- grind guard: must deny foreground grinds ---')
for (const [label, command] of MUST_DENY) {
  expectTrue(`isAgentLoopRunCommand: ${label}`, guard.isAgentLoopRunCommand(command))
}

console.log('--- grind guard: must allow mentions, help, and data heredocs ---')
for (const [label, command] of MUST_ALLOW) {
  expect(`isAgentLoopRunCommand: ${label}`, guard.isAgentLoopRunCommand(command), false)
}

console.log('--- grind guard: tool-level denial ---')
expectDenied(
  'nestedAgentLoopRunReason denies bash foreground',
  guard.nestedAgentLoopRunReason('bash', { command: RUN }),
)
expectDenied(
  'nestedAgentLoopRunReason denies an executed heredoc',
  guard.nestedAgentLoopRunReason('bash', { command: `bash <<'EOF'\n${RUN}\nEOF` }),
)
expectDenied(
  'nestedAgentLoopRunReason denies the pwsh tool',
  guard.nestedAgentLoopRunReason('pwsh', { command: RUN }),
)
expect(
  'background bash stays allowed',
  guard.nestedAgentLoopRunReason('bash', { command: RUN, run_in_background: true }),
  undefined,
)
expect(
  'non-shell tools are ignored',
  guard.nestedAgentLoopRunReason('read', { path: '/tmp' }),
  undefined,
)

// --------------------------------------------------------------- secret guard
const CREDS = '.credentials.yaml'
const DOPPLER_YAML = '.doppler.yaml'

const SECRETS_MUST_DENY = [
  ['canonical doppler yaml', `cat ~/${DOPPLER_YAML}`],
  ['doppler yaml via grep', `grep TOKEN ~/${DOPPLER_YAML}`],
  ['nested doppler yaml via grep -r', `grep -r token ~/.doppler/${DOPPLER_YAML}`],
  ['credentials-local via cat', `cat /Users/me/.dsh/.${CREDS}`],
  ['credentials-local via awk', `awk 1 ~/.dsh/.${CREDS}`],
  ['doppler secrets', 'doppler secrets'],
  ['doppler secrets get', 'doppler secrets get OPENCODE_API_KEY'],
  ['inline DOPPLER_TOKEN', 'DOPPLER_TOKEN=abc doppler run -- true'],
  ['opencode auth.json read', `python3 -c "open('$HOME/.local/share/opencode/auth.json')"`],
  ['credentials-local inside an executed heredoc', `bash <<'EOF'\ncat ~/.dsh/.${CREDS}\nEOF`],
  [
    'credentials-local via command substitution',
    `GO_KEY=$(grep -E '^OPENCODE_GO_API_KEY:' /Users/me/.dsh/.${CREDS} | sed 's/.*: //')`,
  ],
]

const SECRETS_MUST_ALLOW = [
  ['project-scoped doppler run', 'doppler run --project agent-looper --config dev -- agent-check opencode'],
  ['dsh settings read', 'cat ~/.dsh/settings.yaml'],
  ['repo profile read', 'cat .cursor/agent-loop.repo.json'],
  ['listing the dsh dir', 'ls ~/.dsh/'],
]

console.log('--- secret guard: must deny dumps ---')
for (const [label, command] of SECRETS_MUST_DENY) {
  expectTrue(`isSecretDumpCommand: ${label}`, guard.isSecretDumpCommand(command))
}

console.log('--- secret guard: must allow sanctioned commands ---')
for (const [label, command] of SECRETS_MUST_ALLOW) {
  expect(`isSecretDumpCommand: ${label}`, guard.isSecretDumpCommand(command), false)
}
expectDenied(
  'secretDumpReason denies at the tool level',
  guard.secretDumpReason('bash', { command: 'doppler secrets' }),
)

// ------------------------------------------------------------------ lifecycle
function mockCtx() {
  const counts = { section: 0, guard: 0, skill: 0, command: 0 }
  const released = new Set()
  const warnings = []
  const effectDisposers = []
  const disposeListeners = []
  let seq = 0

  const track = (kind) => {
    counts[kind] += 1
    const id = `${kind}#${++seq}`
    return () => released.add(id)
  }

  const ctx = {
    systemPrompt: { section: () => track('section') },
    tools: { guard: () => track('guard') },
    skills: { register: () => track('skill') },
    commands: { register: () => track('command') },
    logger: { warn: (message) => warnings.push(String(message)) },
    effect: (callback) => {
      const disposer = callback()
      if (typeof disposer === 'function') effectDisposers.push(disposer)
      return () => {}
    },
    on: (event, listener) => {
      if (event === 'dispose' && typeof listener === 'function') disposeListeners.push(listener)
      return () => {}
    },
  }

  return {
    ctx,
    counts,
    released,
    warnings,
    cleanup: () => {
      for (const disposer of effectDisposers) disposer()
      for (const listener of disposeListeners) listener()
    },
  }
}

const CONFIG = { skillsDir: './skills', agentLoopBinary: 'agent-loop', blockNestedRun: true }

console.log('--- lifecycle: registrations are released ---')
const live = mockCtx()
let returned
try {
  returned = plugin.apply(live.ctx, CONFIG)
} catch (error) {
  failures.push('apply() threw on a healthy context')
  console.log(`FAIL apply() threw on a healthy context — ${error.message}`)
}
expect('apply registers 1 prompt section', live.counts.section, 1)
expect('apply registers 1 tool guard', live.counts.guard, 1)
expect('apply registers 4 bundled skills', live.counts.skill, 4)
expect('apply registers the loop-scaffold command', live.counts.command, 1)
if (typeof returned === 'function') returned()
live.cleanup()
// Superseded by loop dsh-plugin-guard-hardening: `loop-scaffold` now also hangs off ctx.effect (7 registrations).
expect('releasing the context disposes all 7 registrations', live.released.size, 7)

console.log('--- lifecycle: a missing skillsDir is loud ---')
const missing = mockCtx()
try {
  plugin.apply(missing.ctx, { ...CONFIG, skillsDir: './definitely-missing-skills-dir' })
  expectTrue('missing skillsDir warns through ctx.logger', missing.warnings.length > 0)
} catch (error) {
  expectTrue(`missing skillsDir warns instead of throwing (${error.message})`, false)
}

// ------------------------------------------------------------------- verdict
console.log('')
if (failures.length > 0) {
  console.error(`probe: FAIL — ${failures.length}/${checks} case(s) failed`)
  for (const label of failures) console.error(`  - ${label}`)
  process.exit(1)
}
console.log(`probe: PASS — ${checks} cases hold`)
